# Copyright 2026 HY Chang
# SPDX-License-Identifier: Apache-2.0

name = "appengine-rust"
compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
vars = { RUST_LOG = "info" }
